back/src/main/java/com/woowacourse/teatime/NotFoundScheduleException.java, back/src/main/java/com/woowacourse/teatime/controller/ScheduleController.java, back/src/main/java/com/woowacourse/teatime/controller/dto/ScheduleUpdateRequest.java, back/src/main/java/com/woowacourse/teatime/domain/Schedule.java, back/src/main/java/com/woowacourse/teatime/domain/Schedules.java, back/src/main/java/com/woowacourse/teatime/repository/ScheduleRepository.java, back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java, back/src/main/java/com/woowacourse/teatime/util/Date.java, back/src/test/java/com/woowacourse/teatime/acceptance/AcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/acceptance/ScheduleAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/domain/SchedulesTest.java, back/src/test/java/com/woowacourse/teatime/repository/ScheduleRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
코치 스케줄 수정 구현 
- 코치의 날짜에 해당하는 하루 스케줄을 업데이트한다.
-  스케줄 수정 기능
-  전체적인 예외 처리(커스텀 예외 작성)
reslove: #12
=> [BE] 코치 스케줄 수정 구현

back/src/main/java/com/woowacourse/teatime/config/WebConfig.java
=> [BE] CORS 에러 해결

back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java, back/src/main/java/com/woowacourse/teatime/domain/Reservation.java, back/src/main/java/com/woowacourse/teatime/domain/Schedule.java, back/src/main/java/com/woowacourse/teatime/domain/Schedules.java, back/src/main/java/com/woowacourse/teatime/exception/AlreadyApprovedException.java, back/src/main/java/com/woowacourse/teatime/exception/AlreadyReservedException.java, back/src/main/java/com/woowacourse/teatime/exception/BadRequestException.java, back/src/main/java/com/woowacourse/teatime/exception/InvalidYearException.java, back/src/main/java/com/woowacourse/teatime/exception/NotExistedCrewException.java, back/src/main/java/com/woowacourse/teatime/exception/NotFoundCoachException.java, back/src/main/java/com/woowacourse/teatime/exception/NotFoundException.java, back/src/main/java/com/woowacourse/teatime/exception/NotFoundReservationException.java, back/src/main/java/com/woowacourse/teatime/exception/NotFoundScheduleException.java, back/src/main/java/com/woowacourse/teatime/exception/UnAuthorizedException.java, back/src/main/java/com/woowacourse/teatime/repository/ReservationRepository.java, back/src/main/java/com/woowacourse/teatime/service/ReservationService.java, back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java, back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/domain/ReservationTest.java, back/src/test/java/com/woowacourse/teatime/domain/ScheduleTest.java, back/src/test/java/com/woowacourse/teatime/domain/SchedulesTest.java, back/src/test/java/com/woowacourse/teatime/fixture/DomainFixture.java, back/src/test/java/com/woowacourse/teatime/service/CoachServiceTest.java, back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java, back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
크루가 신청한 면담을 코치가 승인하면 reservation 테이블의 isApproved 컬럼 true로 변경
reslove: #42
=> [BE] 면담 승인 기능 구현

back/src/main/java/com/woowacourse/teatime/config/WebConfig.java
- CORS 포트번호를 3000에서 8080으로 변경한다.
reslove: #60
=> [BE] CORS 포트번호 3000에서 8080으로 변경

back/src/main/java/com/woowacourse/teatime/config/WebConfig.java, back/src/main/java/com/woowacourse/teatime/controller/CoachController.java, back/src/main/java/com/woowacourse/teatime/controller/dto/CoachSaveRequest.java, back/src/test/java/com/woowacourse/teatime/acceptance/CoachAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/controller/CoachControllerTest.java, back/src/test/java/com/woowacourse/teatime/controller/ControllerTest.java
- 코치 등록 api 생성 
- 코치 등록 controller test
- 코치 등록 acceptance test 
reslove: #61
=> [BE] 코치 등록 api 생성

back/src/main/java/com/woowacourse/teatime/controller/dto/ScheduleDto.java
- 일정 조회 응답 타임 포멧 형식 수정
- `2022-07-01T01:00:00` => `2022-07-01T01:00:00.000Z`
reslove: #65
=> [BE] 일정 조회 응답 타임 포멧 형식 수정

back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java, back/src/main/java/com/woowacourse/teatime/util/Date.java, back/src/test/java/com/woowacourse/teatime/acceptance/ScheduleAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/util/DateTest.java
- 이번달 이후의 일정을 조회했을 때 불필요한 이번달 일정을 포함해 반환하는 문제 해결
resolve: #67
=> [BE] 코치 스케줄 조회 오류 해결

back/build.gradle, back/src/test/java/com/woowacourse/teatime/acceptance/AcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/acceptance/DatabaseCleaner.java
- 인수 테스트 격리를 기존에 DirtiesContext를 이용한 방식에서 EntityManger를 이용한 truncate 방식으로 수정
resolve: #44
=> [BE] EntityManger 를 이용한 인수 테스트 격리

front/src/components/CoachTimeList/index.tsx, front/src/components/TimeList/index.tsx, front/src/components/TimeList/styles.ts, front/src/hooks/useCoachTimes.ts, front/src/hooks/useFetch.ts, front/src/pages/Coach/index.tsx, front/src/pages/Coach/styles.ts, front/src/pages/Home/index.tsx, front/src/pages/SelectUser/styles.ts
코치 스케줄 리팩토링
코치 시간 등록, 수정, 삭제 기능 커스텀 훅으로 분리
=> [FE] 코치 스케줄 리팩토링

back/src/main/java/com/woowacourse/teatime/exception/ControllerAdvice.java
* PathVariable 타입이 일치하지 않을 때 예외를 핸들링
resolve: #73
=> [BE] PathVariable 타입이 일치하지 않을 때 예외를 핸들링 하도록 수정

front/src/components/TimeList/index.tsx
=> [FE] 예약하기 api 임시적으로 비활성화

.gitmodules, back/build.gradle
=> [BE] 서브모듈 적용

back/.gitignore, back/build.gradle, back/src/test/java/com/woowacourse/teatime/acceptance/DatabaseCleaner.java
테스트 관련 설정파일 추가한다.
resolve: #90
=> [BE] 테스트 관련 설정파일 추가

back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java, back/src/main/java/com/woowacourse/teatime/domain/Question.java, back/src/main/java/com/woowacourse/teatime/domain/Reservation.java, back/src/main/java/com/woowacourse/teatime/domain/Schedule.java, back/src/main/java/com/woowacourse/teatime/domain/Sheet.java, back/src/main/java/com/woowacourse/teatime/exception/NotFoundCrewException.java, back/src/main/java/com/woowacourse/teatime/repository/QuestionRepository.java, back/src/main/java/com/woowacourse/teatime/repository/SheetRepository.java, back/src/main/java/com/woowacourse/teatime/service/ReservationService.java, back/src/main/java/com/woowacourse/teatime/service/SheetService.java, back/src/test/java/com/woowacourse/teatime/controller/ControllerTest.java, back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java, back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java, back/src/test/java/com/woowacourse/teatime/service/SheetServiceTest.java
- 면담 시트 도메인 설계
- reservation이 생성된 후 면담 시트가 생성되는 로직 추가
resolve: #94
=> [BE] 면담 시트 생성 기능 구현

front/src/api/index.ts
=> [FE] 서버 주소 변경

front/src/App.tsx, front/src/ModalPortal.tsx, front/src/components/Frame/styles.ts, front/src/components/Modal/index.tsx, front/src/components/Textarea/index.tsx, front/src/components/Textarea/styles.ts, front/src/components/TimeList/index.tsx, front/src/components/Title/styles.ts, front/src/constants/index.ts, front/src/pages/InterviewForm/index.tsx, front/src/pages/InterviewForm/styles.ts, front/src/styles/theme.ts
면담 작성 페이지 UI 구현
- 면담 작성 페이지 라우팅 설정
- 면담 작성 페이지 UI 구현
- 면담 내용 상태 핸들링
- 모달 포탈 네이밍 수정 및 경로 변경
=> [FE] 면담 내용 작성 페이지 UI 구현

back/src/main/java/com/woowacourse/teatime/config/WebConfig.java
- 변경된 프론트엔드 url로 cors 설정을 변경해준다.
resolve: #125
=> [BE] 프론트 cors 에러 처리

front/src/components/Textarea/index.tsx, front/src/components/Textarea/styles.ts, front/src/pages/InterviewForm/index.tsx, front/src/styles/theme.ts
면담 작성 form 유효성 검사를 한다
빈 항목이 있을 경우 사용자에게 알려준다.
=> [FE] 면담 작성 form 유효성 검사

front/src/api/index.ts
변경된 teatime 도메인으로 수정
resolve:  #133
=> [FE] 백엔드 주소 변경

back/src/docs/asciidoc/api.adoc, back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java, back/src/main/java/com/woowacourse/teatime/controller/dto/ReservationCancelRequest.java, back/src/main/java/com/woowacourse/teatime/domain/Reservation.java, back/src/main/java/com/woowacourse/teatime/domain/ReservationStatus.java, back/src/main/java/com/woowacourse/teatime/domain/Role.java, back/src/main/java/com/woowacourse/teatime/exception/InvalidCancelException.java, back/src/main/java/com/woowacourse/teatime/exception/NotFoundRoleException.java, back/src/main/java/com/woowacourse/teatime/exception/UnCancellableReservationException.java, back/src/main/java/com/woowacourse/teatime/service/ReservationService.java, back/src/main/resources/static/docs/api.html, back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/controller/ControllerTest.java, back/src/test/java/com/woowacourse/teatime/controller/ReservationControllerTest.java, back/src/test/java/com/woowacourse/teatime/domain/ReservationTest.java, back/src/test/java/com/woowacourse/teatime/domain/RoleTest.java, back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
- 크루와 코치를 식별하여 권한 확인을 할 수 있다.
- 코치가 승인된 상태의 예약을 취소할 수 있다.
- 크루가 승인된 상태의 예약을 취소할 수 있다.
resolve: #111
=> [BE] 면담 취소 기능

front/src/components/CoachTimeList/index.tsx, front/src/components/TimeList/index.tsx
- 하드코딩했던 dateTime 변환을 변경
resolve: #138
=> [FE] dateTime 변환 방식 변경

front/src/components/Board/index.tsx, front/src/components/Board/styles.ts, front/src/components/BoardItem/index.tsx, front/src/components/BoardItem/styles.ts, front/src/components/Calendar/index.tsx, front/src/mocks/data.ts, front/src/mocks/handlers.ts, front/src/pages/Coach/index.tsx, front/src/pages/Coach/styles.ts, front/src/styles/theme.ts, front/src/typings/domain.ts
- 예약 승인 post 요청 모킹
- 승인요청이 성공하면 확정된 일정보드로 이동하도록 상태관리
- 보드 아이템 개수 표시
resolve: #139
=> [FE] 예약 승인 기능 구현

front/src/components/Calendar/index.tsx, front/src/typings/domain.ts
=> [FE] 캘린더 컴포넌트 리팩토링

back/src/main/java/com/woowacourse/teatime/config/WebConfig.java
=> [BE] cors 에러 처리

.github/workflows/backend-build-test.yml
깃허브 액션을 통해 백엔드 테스트를 자동화한다. 
resolve:#150
=> [BE] 백엔드 테스트 자동화 적용

.github/workflows/backend-build-test.yml
깃허브 액션을 통해 백엔드 테스트를 자동화한다. 
resolve:#150
=> [BE] 백엔드 테스트 자동화 적용 

.github/workflows/backend-build-test.yml
github action 서브모듈 토큰 에러 수정
resolve:#150
=> [BE] github action 서브모듈 토큰 에러 수정

front/package.json
=> [FE] 빌드 스크립트 수정

front/src/components/BoardItem/index.tsx, front/src/components/Calendar/index.tsx, front/src/components/CoachTimeList/index.tsx, front/src/components/DateBox/index.tsx, front/src/components/Header/index.tsx, front/src/components/Loading/index.tsx, front/src/components/Modal/index.tsx, front/src/components/SheetInfo/index.tsx, front/src/components/TimeList/index.tsx, front/src/context/ScheduleProvider.tsx, front/src/hooks/useFetch.ts, front/src/index.tsx, front/src/mocks/browser.ts, front/src/mocks/handlers.ts, front/src/pages/Coach/index.tsx, front/src/pages/Crew/index.tsx, front/src/pages/SelectUser/index.tsx, front/src/utils/index.ts
=> [FE] import 정렬

front/src/components/Calendar/index.tsx, front/src/components/Calendar/styles.ts, front/src/components/CoachTimeList/index.tsx, front/src/components/CoachTimeList/styles.ts, front/src/components/DateBox/styles.ts, front/src/components/TimeList/index.tsx, front/src/components/TimeList/styles.ts, front/src/hooks/useTimeList.ts, front/src/pages/Reservation/index.tsx, front/src/pages/Schedule/index.tsx
구현 기능 
- 날짜를 선택하면 시간리스트 컴포넌트가 보이도록 변경
- 월 변경시 시간 리스트 상태가 남아있지 않도록 수정
- 월 변경시 선택된 날짜가 유지되는 버그 수정
=> [FE] 캘린더 월 변경 버그 수정

back/src/main/java/com/woowacourse/teatime/controller/CoachController.java, back/src/test/java/com/woowacourse/teatime/acceptance/CoachAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/controller/CoachControllerTest.java, back/src/test/java/com/woowacourse/teatime/domain/ReservationTest.java
=> [BE] 코치 면담 목록 조회에서 아이디를 헤더로 받도록 수정

front/src/App.tsx, front/src/components/BoardItem/styles.ts, front/src/mocks/data.ts, front/src/mocks/handlers.ts, front/src/pages/Coach/index.tsx, front/src/pages/SelectUser/index.tsx, front/src/typings/domain.ts
예약한 크루 목록 조회 api 연동
resolve: #181
=> [FE] 예약한 크루 목록 조회 api 연동

back/src/main/java/com/woowacourse/teatime/controller/CoachController.java, back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java, back/src/test/java/com/woowacourse/teatime/acceptance/AcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/acceptance/CoachAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/acceptance/ScheduleAcceptanceTest.java
인수테스트를 중심으로 테스트 코드를 리팩터링 한다.
resolve: #168
=> [BE] 테스트 코드 리팩터링

back/src/docs/asciidoc/api.adoc, back/src/main/java/com/woowacourse/teatime/controller/CrewController.java, back/src/main/java/com/woowacourse/teatime/controller/dto/response/CoachFindCrewSheetResponse.java, back/src/main/java/com/woowacourse/teatime/controller/dto/response/CrewFindOwnHistoryResponse.java, back/src/main/java/com/woowacourse/teatime/controller/dto/response/CrewFindOwnSheetResponse.java, back/src/main/java/com/woowacourse/teatime/domain/Reservation.java, back/src/main/java/com/woowacourse/teatime/domain/ReservationStatus.java, back/src/main/java/com/woowacourse/teatime/domain/SheetStatus.java, back/src/main/java/com/woowacourse/teatime/repository/ReservationRepository.java, back/src/main/java/com/woowacourse/teatime/service/ReservationService.java, back/src/main/java/com/woowacourse/teatime/service/SheetService.java, back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/controller/CrewControllerTest.java, back/src/test/java/com/woowacourse/teatime/domain/ReservationTest.java, back/src/test/java/com/woowacourse/teatime/repository/ReservationRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java, back/src/test/java/com/woowacourse/teatime/service/SheetServiceTest.java
- 코치가 크루의 면담 시트를 조회하는 기능 구현
- reservation 내에 시트의 상태를 나타내는 sheet status 추가
resolve: #130
=> [BE] 코치가 크루의 면담 시트를 조회하는 기능 구현

front/src/components/BoardItem/index.tsx, front/src/mocks/handlers.ts, front/src/pages/Coach/index.tsx
- 예약 취소 api 연동
- 취소한 예약 상태관리
resolve: #182
=> [FE] 코치 예약 취소기능 구현

back/src/main/java/com/woowacourse/teatime/controller/CoachController.java, back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java, back/src/main/java/com/woowacourse/teatime/service/ReservationService.java, back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/controller/ControllerTest.java, back/src/test/java/com/woowacourse/teatime/controller/ReservationControllerTest.java, back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
=> [BE] 면담취소 시 아이디, Role을 헤더에 담도록 수정

front/src/App.tsx, front/src/components/SheetInfo/index.tsx, front/src/components/Textarea/index.tsx, front/src/components/Textarea/styles.ts, front/src/constants/index.ts, front/src/pages/ViewSheet/index.tsx
면담 시트 보는 페이지 구현
- 코치가 면담 시트를 보는 페이지 ui 구현
=> [FE] 코치가 면담 시트를 보는 페이지 UI 구현

front/src/components/CoachTimeList/index.tsx, front/src/components/DateBox/index.tsx, front/src/components/Modal/index.tsx, front/src/components/TimeList/index.tsx, front/src/context/ScheduleProvider.tsx, front/src/pages/NotFound/index.tsx
- 예약이 완료되면 재예약이 불가능하도록 상태관리
- 예약 완료 모달컴포넌트 수정
resolve: #201
=> [FE] 재예약이 가능한 문제 수정

front/src/pages/Coach/index.tsx
예약 승인시 승인된 일정 상태를 최근순으로 정렬하는 기능 추가
resolve: #198
=> [FE] 일정 승인시 정렬기능 추가 

front/src/pages/Coach/index.tsx
예약 취소와 승인 전 예약 거절 기능 분리
resolve: #207
=> [FE] 예약 거절 기능 추가

back/src/main/java/com/woowacourse/teatime/domain/Schedule.java, back/src/main/java/com/woowacourse/teatime/repository/ScheduleRepository.java, back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java, back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
=> [BE] 해당 일에 예약이 하나라도 있으면 스케쥴 업데이트가 안되는 문제 수정

front/src/components/Board/index.tsx, front/src/components/BoardItem/index.tsx, front/src/pages/Coach/index.tsx
- 일정 관리 드래그 기능을 임시로 추가
- 승인하기 드래그 기능 추가
- 현재 시간보다 이후 시간은 진행중인 일정으로 드래그 가능하도록 설정
- 그 외의 경우는 모두 이동 불가능하도록 설정
resolve: #214
=> [FE] 일정 드래그 기능 추가

front/src/pages/Coach/index.tsx
- 지난 날짜를 진행중으로 드래그하면 승인 요청이 가는 문제 수정
=> [FE]  드래그 기능 수정

back/src/main/java/com/woowacourse/teatime/service/ReservationService.java
=> [BE] 스케쥴이 승인된 일정에서 진행 중인 일정으로 바뀌지 않는 문제 해결

back/src/main/java/com/woowacourse/teatime/TeatimeApplication.java, back/src/main/java/com/woowacourse/teatime/domain/Reservation.java
Tomcat시간을 KST 설정
resolve: #222
=> [BE] Tomcat시간을 KST 설정

front/src/components/SheetInfo/index.tsx
면담 시트 컴포넌트 리팩토링
면담 시트 컴포넌트 버튼 로직 변경
=> 면담 시트 컴포넌트 리팩토링

back/src/main/java/com/woowacourse/teatime/controller/CrewController.java, back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/controller/CrewControllerTest.java
=> [BE] 크루가 자신의 면담 히스토리를 조회할때 crewId를 헤더로 받도록 수정

front/src/components/Calendar/index.tsx, front/src/components/Calendar/styles.ts, front/src/components/DateBox/index.tsx, front/src/components/DateBox/styles.ts, front/src/context/ScheduleProvider.tsx, front/src/utils/index.ts
- 지난 날짜는 일정 등록/ 예약이 불가능하도록 수정 
- 날짜형식 리팩토링
resolve: #241
=> [FE] 지난 날짜는 예약 불가능하도록 수정

front/src/assets/trash.svg, front/src/components/TableRow/index.tsx, front/src/components/TableRow/styles.ts, front/src/pages/CrewHistory/index.tsx, front/src/pages/CrewHistory/styles.ts
크루 히스토리 면담 내용보기 및 면담 삭제 기능
- 면담 내용을 볼 수 있다
- 면담을 취소 할 수 있다.
- day.js 수정하기
- 휴지통 아이콘 추가
=> [FE] 크루 히스토리 면담 내용보기 및 면담 삭제 기능

front/src/components/BoardItem/styles.ts, front/src/pages/NotFound/styles.ts
=> [FE] 누락된 색상 변경

back/src/main/java/com/woowacourse/teatime/exception/ControllerAdvice.java, back/src/main/resources/console-appender.xml, back/src/main/resources/dev-warn-appender.xml, back/src/main/resources/file-error-appender.xml, back/src/main/resources/file-info-appender.xml, back/src/main/resources/logback-spring.xml, back/src/main/resources/prod-warn-appender.xml
로깅 전략을  개발 환경에 따라 다르게 한다. 
```sql
local
INFO - All 
```
```sql
dev
INFO: 실행흐름, 메서드 동작 시간  
WARN: handled error, unhandled error (400, 500)
```
```sql
prod 
INFO: 실행흐름, 메서드 동작 시간 
WARN: handled error
ERROR: unhandled error
```
resolve: #245
=> [BE] 로깅 전략 고도화

.github/workflows/build.yml, back/build.gradle
build.gradle에 소나큐브 설정 추가
resolve: #269
=> SonarQube를 적용

front/webpack.config.ts
=> [FE] bundle analyzer 비활성화

front/src/pages/Certification/index.tsx
=> [FE] 로그인 api 연결

back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Crew.java
- 슬랙 `이름` 정보의 최대 길이에 맞게 name column의 최대 길이 수정
=> [BE] 특정 인물만 슬랙 로그인에 실패하는 에러 수정

front/webpack.config.ts
- analyzer 옵션을 static으로 설정 (디폴트는 server)
- 빌드시 analyzer로 인해 빌드가 끝나지 않는 문제 수정
- 분석 결과를 서버로 띄우지않고 dist/report.html 에서 확인할수있도록 변경
resolve: #282
=> [FE] bundle analyzer 설정 수정

front/src/pages/Crew/index.tsx
=> [FE] api 오타 수정

front/src/pages/Certification/index.tsx
=> [FE] 로그인 path 수정

back/src/main/java/com/woowacourse/teatime/auth/controller/dto/LoginResponse.java, back/src/main/java/com/woowacourse/teatime/auth/service/AuthService.java, back/src/main/java/com/woowacourse/teatime/exception/UnAuthorizedException.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/CoachControllerV2.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/CrewControllerV2.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/ReservationControllerV2.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/ScheduleControllerV2.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/ReservationApproveRequestV2.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/ReservationCancelRequest.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/ReservationReserveRequestV2.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Reservation.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/SheetService.java
* 로그인이 포함 된 컨트롤러를 구현한다.
* 서비스 로직이 약간 달라진 경우 v2 메서드를 작성한다.
* 로그인 후 응답값에 유저의 image와 name을 보내준다.
v2 패키지로 따로 빼지 않은 이유: import가 많이 깨질 것 같음
테스트코드 미포함
resolve: #289
=> [BE] 로그인이 포함 된 컨트롤러를 구현한다.

front/src/App.tsx, front/src/components/BoardItem/index.tsx, front/src/pages/Coach/index.tsx
=> [FE] 히스토리 시트 이동 핸들러 연결

front/src/App.tsx, front/src/pages/Coach/index.tsx
- Schdule 페이지 id 제거
resolve: #306
=> [FE] 스케쥴 페이지 route 수정

back/src/main/java/com/woowacourse/teatime/auth/support/UserArgumentResolver.java, back/src/main/java/com/woowacourse/teatime/auth/support/UserAuthenticationPrincipal.java, back/src/main/java/com/woowacourse/teatime/auth/support/dto/UserRoleDto.java, back/src/main/java/com/woowacourse/teatime/teatime/config/WebConfig.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/ReservationControllerV2.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java
* UserArgumentResolver를 생성한다.
* 취소 로직에서 모든 유저에 대해서 파라미터로 받을 수 있도록 컨트롤러 수정
resolve: #305
=> [BE] UserArgumentResolver를 만들고 면담 취소 api에 적용

front/src/components/Card/styles.ts, front/src/pages/Crew/styles.ts
- 크루 메인페이지 하단 margin 추가
- 코치 카드 높이수정
resolve:  #312
=> [FE] 크루 메인페이지 스타일 수정

front/src/components/Header/index.tsx, front/src/components/Header/styles.ts
로그인시 헤더에 슬랙 프로필 이미지 추가
resolve: #309
=> [FE] 헤더 프로필 이미지 추가

front/src/components/BackButton/styles.ts, front/src/components/HistoryItem/index.tsx, front/src/components/ReservationInfo/index.tsx, front/src/components/ReservationInfo/styles.ts, front/src/components/Sheet/index.tsx, front/src/pages/CrewSheet/index.tsx
=> [FE] 시트 컴포넌트 피드백 반영

front/src/App.tsx, front/src/AuthRoute.tsx, front/src/components/CoachTimeList/index.tsx, front/src/components/Header/index.tsx, front/src/components/TimeList/index.tsx, front/src/context/UserProvider.tsx, front/src/pages/Certification/index.tsx, front/src/pages/Coach/index.tsx, front/src/pages/CoachSheet/index.tsx, front/src/pages/Crew/index.tsx, front/src/pages/CrewHistory/index.tsx, front/src/pages/CrewSheet/index.tsx, front/src/pages/HistorySheet/index.tsx, front/src/pages/NotFound/index.tsx, front/src/pages/Reservation/index.tsx, front/src/pages/Schedule/index.tsx, front/src/typings/domain.ts
- 유저 데이터 context로 관리
- 권한에 따라 라우팅 접근 방지
resolve: #304
=> [FE] 권한에 따른 라우팅 개선 

front/src/pages/HistorySheet/index.tsx
historyList가 없을때 예외처리 
resolve: #319
=> [FE] 히스토리가 없는 경우 임시예외처리

front/jest.config.ts, front/package-lock.json, front/package.json, front/src/utils/__test__/date.test.ts, front/src/utils/date.test.ts, front/tsconfig.json
- jest 환경 설정
- 날짜 유틸 단위 테스트 추가 
resolve: #325
=> [FE] 단위 테스트 추가 

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachApprovedReservationDto.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachNotApprovedReservationDto.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachReservationDto.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachReservationsResponse.java
상태가 approved인 면담 response에 sheet 상태를 포함하도록 수정
resolve: #265
=> [BE] 상태가 approved인 면담 response에 sheet 상태를 포함하도록 수정

front/src/App.tsx, front/src/components/TableRow/index.tsx, front/src/components/TableRow/styles.ts, front/src/pages/CrewHistory/index.tsx
=> [FE] 히스토리 삭제 시 리랜더링 기능

front/src/pages/Coach/index.tsx, front/src/pages/Home/index.tsx
재접속시 role에 따른 라우팅 변경
resolve: #336
=> [FE] 재접속시 role에 따른 라우팅 변경

front/src/context/UserProvider.tsx, front/src/pages/Coach/index.tsx, front/src/pages/Crew/index.tsx
- 토큰이 만료됐을때 에러처리 
- 코치/크루 메인 토큰만료처리
resolve: #337
=> [FE] 토큰이 만료됐을때 에러처리  

front/src/pages/Coach/index.tsx
=> [FE] 면담 완료기능 연동

front/src/components/Dropdown/index.tsx, front/src/components/Dropdown/styles.ts, front/src/components/Header/index.tsx, front/src/components/Header/styles.ts, front/src/pages/CrewHistory/index.tsx, front/src/pages/HistorySheet/index.tsx
dropdown 컴포넌트 추가
resolve: #340
=> [FE] dropdown 컴포넌트 추가

front/src/components/BoardItem/index.tsx, front/src/components/BoardItem/styles.ts, front/src/pages/Certification/index.tsx, front/src/pages/Coach/index.tsx, front/src/pages/Crew/index.tsx, front/src/pages/Home/index.tsx, front/src/typings/domain.ts
- 서버 상태에 따라 작성중인 시트는 이동 불가 및 음영처리 
- 
resolve: #343
=> [FE] 작성중인 시트 음영처리 기능

front/src/pages/Certification/index.tsx
=> [FE] 인증페이지에 로딩컴포넌트 추가

front/src/components/TableRow/index.tsx
=> [FE] history status 삭제 기능 수정

front/src/components/Snackbar/styles.ts
- 불필요한 css 코드 제거 및 위치가 중앙이 아닌 문제 수정
<br>
resolve: #352
=> [FE] snackbar 스타일 수정

front/src/components/Sheet/index.tsx, front/src/components/Title/index.tsx, front/src/components/Title/styles.ts, front/src/pages/Reservation/index.tsx, front/src/pages/Schedule/index.tsx, front/src/styles/common.ts
- 캘린더/날짜 선택시 텍스트가 변경되도록 수정
- 디자인 일부 수정
<br>
<br>
- 디자인 아이디어
<br>
resolve: #353
=> [FE] title 컴포넌트 수정

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/ScheduleUpdateRequest.java
테스트 실패 오류 수정 및 설정 파일 업데이트
* dto에 기본생성자가 없는 부분 수정
* 엑세스 토큰 만료 기간 조정
자잘한 수정이라 이슈는 따로 파지 않겠습니다!
=> [BE] 테스트 실패 오류 수정 및 설정 파일 업데이트

front/src/components/Calendar/styles.ts, front/src/components/Card/styles.ts, front/src/components/DateBox/styles.ts, front/src/components/Frame/styles.ts, front/src/components/Header/index.tsx, front/src/components/ReservationTimeList/styles.ts, front/src/components/Title/styles.ts, front/src/pages/Crew/styles.ts, front/src/pages/Home/index.tsx, front/src/pages/Home/styles.ts, front/src/styles/GlobalStyle.ts, front/src/styles/common.ts, front/src/styles/theme.ts
- 모바일 환경에서 이용이 불가능한 문제 수정
- 예약 과정에 대한 모바일 대응
지금 모바일에서는 이용이 아예 불가능하므로 우선 예약자는 이용 가능하도록 반응형 적용했습니다.
resolve: #371
=> [FE] 반응형 적용

front/public/index.html
meta tag 수정
* 작은 수정이라 이슈는 생략했습니다.
=> [FE] meta tag 수정

front/src/styles/theme.ts
=> [FE] media query 적용이 안되는 문제 수정

front/.gitignore, front/src/api/index.ts
=> [FE] dev, prod URL 변경 

front/src/pages/Home/index.tsx
- slack redirect url 수정 
resolve: #387
=> [FE] slack redirect url 수정

back/src/main/java/com/woowacourse/teatime/teatime/config/WebConfig.java
=> [BE] CORS url 수정

front/package-lock.json, front/src/components/BackButton/styles.ts, front/src/components/Frame/styles.ts, front/src/components/HistoryItem/styles.ts, front/src/components/ReservationInfo/index.tsx, front/src/components/Textarea/styles.ts, front/src/pages/CoachSheet/index.tsx, front/src/pages/CrewSheet/index.tsx, front/src/pages/HistorySheet/index.tsx, front/src/pages/Reservation/index.tsx, front/src/pages/Schedule/index.tsx, front/src/styles/common.ts
- word spacing 제거
- overflow scroll 추가
- 히스토리 블록 스타일 변경
- 뒤로가기 버튼 스타일 변경
- textarea 보더레디어스 4px -> 8px
- textarea 보더 굵기 2px로 하니 어색함... 스타일은 더 고민해봐야 할듯 
resolve: #401
=> [FE] 면담시트 컴포넌트 스타일 수정

back/src/main/java/com/woowacourse/teatime/TeatimeApplication.java, back/src/main/java/com/woowacourse/teatime/teatime/config/SchedulerConfig.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Reservation.java, back/src/main/java/com/woowacourse/teatime/teatime/exception/UnableToInProgressReservationException.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/scheduler/SchedulerService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ReservationAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/domain/ReservationTest.java, back/src/test/java/com/woowacourse/teatime/teatime/fixture/DomainFixture.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/ReservationRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/scheduler/SchedulerServiceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
=> [BE] 스프링 스케줄러 구현

back/src/docs/asciidoc/api.adoc, back/src/main/java/com/woowacourse/teatime/teatime/controller/CoachController.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindOwnHistoryResponse.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CoachAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ReservationAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/controller/CoachControllerTest.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/ReservationRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
구현 기능
- 코치에 해당하는 취소, 종료된 면담 목록 조회 기능 구현
- 코치가 자신의 면담 히스토리를 조회하는 기능 구현
resolve: #417
=> [BE] 코치가 자신의 면담 히스토리를 조회하는 기능 구현

front/src/components/TableRow/index.tsx, front/src/pages/CoachHistory/index.tsx, front/src/pages/CrewHistory/index.tsx
=> [FE]  api 오타 수정 및 삭제 버튼 제거

front/src/components/BoardItem/styles.ts, front/src/components/ReservationInfo/styles.ts, front/src/components/ReservationTimeList/styles.ts, front/src/components/Title/styles.ts, front/src/pages/CoachHistory/index.tsx, front/src/pages/CoachSheet/styles.ts, front/src/pages/CrewHistory/index.tsx, front/src/pages/Schedule/index.tsx, front/src/styles/theme.ts
7-72eb9e69-b71e-4f2c-b3b6-588b0d238ad0.png">
=> [FE] 3차 QA 스타일 수정

front/src/components/EmptyContent/index.tsx, front/src/components/HistoryItem/index.tsx, front/src/components/ReservationInfo/index.tsx, front/src/components/TableRow/index.tsx, front/src/pages/CoachMain/index.tsx
- 누락된 alt 추가 및 수정
resolve: #446
=> [FE] 누락된 alt 추가 및 수정

back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Crew.java
=> [BE] slack id가 제대로 저장되지 않는 문제 해결

front/src/pages/CrewHistory/index.tsx
- 크루 히스토리 조회 에러 수정
- 머지 과정에서 핸들러가 누락된 에러 수정
resolve: #462
=> [FE] 크루 히스토리 조회 에러 수정

back/src/docs/asciidoc/coach.adoc, back/src/docs/asciidoc/crew.adoc, back/src/main/java/com/woowacourse/teatime/teatime/controller/CoachController.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/CrewController.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/ReservationController.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/CoachUpdateProfileRequest.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/CrewUpdateProfileRequest.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Crew.java, back/src/main/java/com/woowacourse/teatime/teatime/exception/InvalidProfileInfoException.java, back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/CrewService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CoachAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/controller/CoachControllerTest.java, back/src/test/java/com/woowacourse/teatime/teatime/controller/ControllerTestSupporter.java, back/src/test/java/com/woowacourse/teatime/teatime/controller/CrewControllerTest.java, back/src/test/java/com/woowacourse/teatime/teatime/controller/ReservationControllerTest.java, back/src/test/java/com/woowacourse/teatime/teatime/domain/CoachTest.java, back/src/test/java/com/woowacourse/teatime/teatime/domain/CrewTest.java, back/src/test/java/com/woowacourse/teatime/teatime/fixture/DomainFixture.java, back/src/test/java/com/woowacourse/teatime/teatime/infrastructure/SchedulerTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/CoachServiceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/CrewServiceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
- 코치 닉네임 수정 기능을 구현.
- 크루 닉네임 수정 기능을 구현.
resolve: #459
=> [BE] 닉네임 수정 기능

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindOwnHistoryResponse.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CrewFindOwnHistoryResponse.java
히스토리를 조회할 때 최신순으로 볼 수 있도록 수정한다.
=> [BE] 히스토리를 조회할 때 최신순으로 볼 수 있도록 수정

front/src/App.tsx, front/src/api/coach.ts, front/src/api/crew.ts, front/src/components/Header/index.tsx, front/src/components/Header/styles.ts, front/src/components/Modal/index.tsx, front/src/components/Modal/styles.ts, front/src/components/ReservationTimeList/index.tsx, front/src/components/ReservationTimeList/styles.ts, front/src/components/ScheduleTimeList/styles.ts, front/src/components/Snackbar/styles.ts, front/src/components/TableRow/index.tsx, front/src/context/UserProvider.tsx, front/src/pages/CoachMain/index.tsx, front/src/pages/CrewHistory/index.tsx, front/src/pages/CrewMain/index.tsx, front/src/pages/CrewSheet/index.tsx, front/src/pages/HistorySheet/index.tsx, front/src/styles/common.ts
- 취소된 상태일때 시트보기 api 추가
- 취소된 상태로 변경되면 맨 위로 올리기
<br>
- 닉네임 변경하는 기능 모달로 표시
- 글자수, 공백일 경우 유효성 검사
=> [FE] 변경된 api 수정 및 닉네임 변경 기능 추가

back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/Alarm.java, back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/SlackAlarm.java, back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmTitle.java, back/src/test/java/study/StringSplitTest.java
- 알람 내용에 따라 알람 색상을 지정
- 알람이 크루에게만 두번 가는 문제 해결
resolve: #457
=> [BE] 알람 내용에 따라 알람 색상을 지정

front/src/pages/Home/index.tsx
슬랙 url 워크스페이스 수정
resolve: #469
=> [FE] 슬랙 url 워크스페이스 수정

front/src/pages/Home/index.tsx
=> [FE] 슬랙 url 수정

front/src/components/Header/styles.ts, front/src/components/Modal/styles.ts, front/src/components/ReservationTimeList/index.tsx, front/src/components/ScheduleTimeList/index.tsx, front/src/pages/Reservation/index.tsx, front/src/pages/Schedule/index.tsx
=> [FE] timelist 컴포넌트 리팩토링

front/src/pages/HistorySheet/index.tsx
=> [FE] 히스토리 시트가 없을 경우 빈 화면 표시

back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java, back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java, back/src/test/java/com/woowacourse/teatime/teatime/domain/CoachTest.java
이름이 변경되면 description도 변경되도록 수정
=> [BE] 이름이 변경되면 description도 변경되도록 수정

front/src/pages/Home/index.tsx
redirect url env 설정
resolve: #480
=> [FE] redirect url env 설정

back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java
- 알람 트랜잭션 전파 수준 변경(Required-new)
=> [BE] 알람 트랜잭션 전파 수준 변경

back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
=> [BE] 시간 지연 오류 테스트 - 알람 주석 

back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
=> [BE] 시간 지연 오류 테스트 - 비동기 처리 

back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Crew.java
유저의 슬랙 아이디가 다르면 업데이트 시켜주도록 변경
resolve: #487
=> [BE] 유저의 슬랙 아이디가 다르면 업데이트 시켜주도록 변경

front/src/components/ScheduleTimeList/index.tsx, front/src/components/ScheduleTimeList/styles.ts, front/src/utils/__test__/date.test.ts
- 코치 일정 등록시, 당일의 지난 시간은 등록되지 않도록 수정 
resolve: #477
=> [FE] 코치 일정 등록 수정

front/src/styles/GlobalFonts.ts
- 폰트 최적화
- swap 설정
resolve: #493
=> [FE] 폰트 최적화

front/src/api/auth.ts, front/src/api/coach.ts, front/src/api/crew.ts, front/src/api/index.ts, front/src/api/reservation.ts, front/src/components/Calendar/styles.ts, front/src/components/Header/styles.ts, front/src/hooks/useFetch.ts, front/src/pages/CoachMain/index.tsx, front/src/pages/HistorySheet/index.tsx, front/src/pages/Reservation/index.tsx
- api 파일 -> export로 변경
- 코치가 보는 크루 히스토리 제목 변경 -> "안의 면담 내용"
- 아이콘 사이즈 명시
- 달력 날짜 깜빡거림 해결
=> [FE] QA 수정사항 반영

back/src/main/java/com/woowacourse/teatime/exception/ControllerAdvice.java, back/src/main/java/com/woowacourse/teatime/teatime/config/AsyncConfig.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Crew.java, back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java, front/src/api/auth.ts, front/src/api/coach.ts, front/src/api/crew.ts, front/src/api/index.ts, front/src/api/reservation.ts, front/src/components/Calendar/styles.ts, front/src/components/Header/styles.ts, front/src/components/ScheduleTimeList/index.tsx, front/src/components/ScheduleTimeList/styles.ts, front/src/hooks/useFetch.ts, front/src/pages/CoachMain/index.tsx, front/src/pages/HistorySheet/index.tsx, front/src/pages/Reservation/index.tsx, front/src/styles/GlobalFonts.ts, front/src/utils/__test__/date.test.ts
release: v1.0.1 배포
- 알람 비동기 처리 
- 히스토리 타이틀 수정
- 폰트 속성 추가 
- 달력 날짜 깜빡거림 해결 
- 아이콘 사이즈 명시
=> release: v1.0.1 배포

front/src/constants/index.ts, front/src/pages/CrewMain/index.tsx, front/src/utils/cacheFetch.ts
=> [FE] 데이터 캐싱하는 기능

.github/workflows/frontend-ci.yml
-  frontend test, build workflow 추가
resolve:#497
=> [FE] frontend ci 추가

.github/workflows/frontend-ci.yml
- workflow env 설정 추가
resolve: #502
=> [FE] workflow env 설정.  

.github/workflows/frontend-ci.yml
=> [FE] workflow 수정

front/src/App.tsx, front/src/components/Loading/index.tsx, front/src/pages/Certification/index.tsx, front/webpack.config.ts
- 라우팅 기반 코드스플리팅 적용
resolve: #514
=> [FE] 코드 스플리팅 적용

front/src/pages/Home/index.tsx, front/src/pages/Home/styles.ts
- 팀원소개 임시적으로 삭제
- 일부 스타일 조정
resolve: #512
=> [FE] 랜딩페이지 스타일 수정

front/src/components/Board/styles.ts, front/src/components/Card/styles.ts, front/src/components/Frame/styles.ts, front/src/components/Header/styles.ts, front/src/components/Loading/styles.ts, front/src/pages/Certification/index.tsx, front/src/pages/Home/styles.ts, front/src/pages/NotFound/styles.ts, front/src/styles/GlobalStyle.ts, front/src/styles/theme.ts
- Frame, body 스타일 수정
- 슬랙 요청 취소시 임시 에러처리
resolve: #300
=> [FE] 전체적인 스타일 수정

front/src/pages/Schedule/index.tsx
- 다음달 스케줄 로드시 깜빡거림 이슈 수정#518 
resolve: #518
=> [FE] 다음달 스케줄 로드시 깜빡거림 이슈 수정

back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/Scheduler.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java
- 리마인드 알람 시간을 전날 18시로 수정
- 리마인드할 면담의 범위를 승인된 면담 중 다음날 면담으로 한정
resolve: #508
=> [BE] 리마인드 알람 시간과 알람에 포함되는 면담 범위 수정

front/src/components/TableRow/index.tsx, front/src/pages/CoachHistory/index.tsx, front/src/typings/domain.ts
코치 히스토리에서 완료된 면담 시트 보여주는 기능
resolve: #520
=> [FE] 코치 히스토리에서 완료된 면담 시트 보여주는 기능

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindOwnHistoryResponse.java, back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/Scheduler.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java, front/src/components/TableRow/index.tsx, front/src/pages/CoachHistory/index.tsx, front/src/pages/Schedule/index.tsx, front/src/typings/domain.ts
release: v1.1.0 배포
- 다음달 (코치)스케줄 로드시 깜빡거림 이슈 수정
- 코치 히스토리에서 완료된 면담 시트가 보이도록 수정
- 리마인드 알람 시간과 알람에 포함되는 면담 범위 수정
- 코치 히스토리 조회시 crewId 추가
=> release: v1.1.1 배포

front/src/components/TableRow/index.tsx, front/src/pages/CoachHistory/index.tsx
=> [FE] 히스토리 조회 에러 수정

front/src/components/TableRow/index.tsx, front/src/pages/CoachHistory/index.tsx
release: v1.1.2 배포
히스토리 조회 에러 수정
=>  release: v1.1.2 배포

back/src/main/java/com/woowacourse/teatime/teatime/aspect/QueryCountInspector.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/CoachUpdateProfileRequest.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java, back/src/main/java/com/woowacourse/teatime/teatime/exception/InvalidProfileInfoException.java, back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CoachAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/controller/CoachControllerTest.java, back/src/test/java/com/woowacourse/teatime/teatime/domain/CoachTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/CoachServiceTest.java
- 코치 프로필 수정에 설명 수정 기능 추가
resolve: #531
=> [BE] 코치 프로필(이름, 설명) 일괄 수정 기능 

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CrewFindOwnCanceledSheetResponse.java
=> [BE] response 필드 네이밍 변경

front/src/components/Sheet/index.tsx, front/src/components/Sheet/styles.ts, front/src/components/TableRow/index.tsx, front/src/components/Textarea/index.tsx, front/src/components/Textarea/styles.ts, front/src/pages/CoachHistory/index.tsx, front/src/pages/CoachSheet/index.tsx, front/src/pages/CrewHistory/index.tsx, front/src/pages/CrewSheet/index.tsx, front/src/pages/HistorySheet/index.tsx, front/src/typings/domain.ts
- 코치 히스토리에서 완료된 면담은 시트를 볼 수 있다
- 크루 시트에서 임시저장된 상태이고 면담이 진행 중이라면 임시저장 및 제출할 수 없다
- 면담 시트 제목 수정 -> "안(ahn)의 면담 내용" 
resolve: #535
=> [FE] 5차 QA 수정사항 반영

back/src/main/java/com/woowacourse/teatime/auth/service/AuthService.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Crew.java
slack 이미지가 변경된 경우 로그인시 업데이트 되는 기능 구현
resolve: #540
=> [BE] slack 이미지 로그인시 업데이트 되는 기능 구현

back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/Scheduler.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java, back/src/test/java/com/woowacourse/teatime/teatime/infrastructure/SchedulerTest.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/ReservationRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
면담 시트를 전날까지 제출하지 않아도 자동취소 되지 않도록 수정
resolve: #543
=> [BE] 면담 시트 미제출시 자동취소 기능 삭제

back/src/main/java/com/woowacourse/teatime/teatime/controller/CoachController.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachProfileResponse.java, back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CoachAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/controller/CoachControllerTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/CoachServiceTest.java
* 코치 자신의 프로필을 조회하는 기능을 구현한다.
* 테스트를 추가한다.
resolve: #541
=> [BE] 코치 자신의 프로필을 조회하는 기능 구현

back/src/main/java/com/woowacourse/teatime/teatime/controller/CrewController.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/controller/CrewControllerTest.java
- 코치가 크루의 히스토리를 조회하는 api를 잠시 막기 위해 주석처리
- 그와 관련된 테스트도 주석처리
resolve: #539
=> [BE] 코치가 크루의 히스토리를 조회하는 기능 막기

back/src/main/java/com/woowacourse/teatime/auth/service/AuthService.java
- 전 기수를 코치로 등록하도록 수정
resolve: #537
=> [BE] 전 기수를 코치로 등록하도록 수정

front/src/App.tsx, front/src/api/coach.ts, front/src/components/BoardItem/index.tsx, front/src/components/BoardItem/styles.ts, front/src/components/Header/index.tsx, front/src/constants/index.ts, front/src/pages/CoachProfile/index.tsx, front/src/pages/CoachProfile/styles.ts, front/src/typings/domain.ts
- 코치 프로필을 수정할 수 있다 ( 이름, 설명)
- 크루 히스토리 전체 내용보기 안됨
=> [FE] 코치 프로필 수정 페이지 구현

back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/Scheduler.java
예약을 확인하는 스케줄러를 10시부터 22시까지 실행되도록 수정
resolve: #554
=> [BE] 승인된 예약을 진행중인 예약으로 변경하는 스케쥴러 수정

front/src/components/DateBox/index.tsx, front/src/components/DateBox/styles.ts, front/src/pages/Reservation/index.tsx, front/src/pages/Schedule/index.tsx
=> [FE] 코치 스케줄 등록 범위 수정

back/src/main/java/com/woowacourse/teatime/teatime/infrastructure/Scheduler.java, front/src/components/DateBox/index.tsx, front/src/components/DateBox/styles.ts, front/src/pages/Reservation/index.tsx, front/src/pages/Schedule/index.tsx
release: v1.3.0 배포
- 주말과 저녁 시간에도 일정을 등록할 수 있는 기능
=> release: v1.3.0 배포

front/src/pages/Home/styles.ts, front/src/styles/GlobalStyle.ts, front/src/styles/theme.ts
- 모바일에서 아래 두가지 경우 스크롤이 생기지 않게 수정했습니다
resolve: #557
=> 모바일뷰 스타일 수정

front/src/components/DateBox/index.tsx, front/src/components/DateBox/styles.ts, front/src/components/ReservationTimeList/styles.ts, front/src/components/ScheduleTimeList/styles.ts
캘린더에서 예약 마감된 상태 표시
resolve: #559
=> [FE] 예약 마감된 날짜 상태 표시

front/src/components/Card/styles.ts, front/src/pages/CrewMain/styles.ts, front/src/styles/theme.ts
- 카드 크기가 짤리는 경우가 없도록 카드 배치 설정
- 태블릿에서도 description이 보이도록 수정
resolve: #570
=> [FE] 코치리스트 반응형 수정

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindResponse.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ScheduleAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/controller/CoachControllerTest.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/ScheduleRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/CoachServiceTest.java
크루 메인뷰에서 예약 가능한 코치만 따로 표시해주도록 api 수정
- resolve: #562
=> [BE] 크루 메인뷰에서 예약 가능한 코치만 따로 표시해주도록 api 수정

front/src/components/Card/index.tsx, front/src/components/Card/styles.ts, front/src/constants/index.ts, front/src/pages/CrewMain/index.tsx, front/src/typings/domain.ts
- 스케줄이 있을 경우 카드에 표시
- 캐싱 시간 5분으로 수정
resolve: #565
=> [FE] 코치 리스트에서 스케줄이 있을 경우 카드에 표시하는 기능

front/public/index.html
=> [FE] 채널톡을 적용한다.

back/src/main/java/com/woowacourse/teatime/teatime/controller/ScheduleController.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ScheduleService.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ScheduleAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/controller/ScheduleControllerTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ScheduleServiceTest.java
- 요청을 list로 받도록 수정
resolve: #592
=> [BE] 여러 날짜의 스케줄을 한번에 업데이트 할 수 있도록 수정

back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmTitle.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/dto/SlackAlarmDto.java, back/src/test/java/com/woowacourse/teatime/teatime/service/CrewServiceTest.java
- 시트 제출시 알람이 가는 기능 추가
- 모든 알람에 티타임 바로가기 링크를 추가
resolve: #580
=> [BE] 시트 제출 알람 추가

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindResponse.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/CoachRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/dto/CoachWithPossible.java, back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/CoachRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/ScheduleRepositoryTest.java
크루 메인뷰에서 발생하는 1+N 문제 해결
- resolve: #576
=> [BE] 크루 메인뷰에서 발생하는 1+N 문제 해결

back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/dto/SlackAlarmDto.java
- 슬랙 알람 티타임 바로가기 링크 형식 수정
- 시트 작성시 알람이 전송되도록 수정
resolve: #580
=> [BE] 슬랙 알람 티타임 바로가기 링크 수정

front/src/components/Filter/index.tsx, front/src/components/Filter/styles.ts, front/src/pages/CoachHistory/index.tsx, front/src/pages/CrewHistory/index.tsx, front/src/pages/CrewHistory/styles.ts
=> [FE] 히스토리 필터링 기능 추가

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindResponse.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/CoachRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/dto/CoachWithPossible.java, back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/CoachRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/ScheduleRepositoryTest.java
=> [BE] 크루메인뷰에서 발생하는 에러 수정

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindResponse.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/CoachRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/dto/CoachWithPossible.java, back/src/main/java/com/woowacourse/teatime/teatime/service/CoachService.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/CoachRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/ScheduleRepositoryTest.java
크루 메인뷰에서 발생하는 1+N 문제 해결
- resolve: #576
=> [BE] 크루 메인뷰에서 발생하는 1+N 문제 해결 

back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java
코치 메인뷰에서 발생하는 1+N 문제 해결
- resolve: #533
=> [BE] 코치 메인뷰에서 발생하는 1+N 문제 해결

front/src/components/ScheduleTimeList/styles.ts, front/src/pages/Schedule/index.tsx
=> [FE] 다중선택 임시적으로 비활성화

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindCrewSheetResponse.java
- 코치가 크루 면담시트 조회하는 api 수정(coachName, coachImage 대신 crewName, crewImage를 응답값에 넘겨주도록 수정)
- 참고: N+1 문제가 발생할 수 있다.
- resolve: #608
=> [BE] 코치가 크루 면담시트 조회하는 api 수정

front/src/api/crew.ts, front/src/pages/CoachSheet/index.tsx, front/src/typings/domain.ts
코치가 보는 크루시트 정보 수정
resolve: #609
=> [FE] 코치가 보는 크루시트 정보 수정

back/build.gradle
=> [BE] 서브모듈 설정 적용

back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/jdbc/ScheduleDao.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ScheduleService.java, back/src/main/java/com/woowacourse/teatime/util/Date.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ReservationAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ScheduleAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/ScheduleRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/jdbc/ScheduleDaoTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ScheduleServiceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/support/RepositoryTest.java
=> [BE] fetch join 적용, n+1 문제 해결

front/src/components/CalendarSelectList/styles.ts, front/src/components/MultipleTimeList/styles.ts, front/src/components/ScheduleTimeList/styles.ts, front/src/hooks/useSelectList.ts, front/src/pages/CoachSheet/styles.ts, front/src/pages/Schedule/index.tsx, front/src/pages/Schedule/styles.ts
- 다중선택 기능 수정 후 활성화
- 예약된 일정이 있는경우 alert를 스낵바로 대체
- 버튼 색상 변경
resolve: #613
=> [FE] 다중선택 기능 활성화

front/src/components/Card/styles.ts, front/src/components/Dropdown/styles.ts
- 예약하기 버튼이 깨지는 부분 수정
- 드롭다운 우측 짤리는 부분 수정
=> [FE] 소형 모바일 스타일 수정

front/src/components/Card/index.tsx, front/src/components/Card/styles.ts, front/src/pages/CoachProfile/index.tsx, front/src/pages/CoachProfile/styles.ts
- 미리보기 구현
- 영어로 띄어쓰기 없이 입력시 미리보기에 한줄로보임 -> 띄어쓰기 하면 됨
resolve: #618
=> [FE] 코치 프로필 미리보기 구현

back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ScheduleService.java, back/src/main/java/com/woowacourse/teatime/util/Date.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/ScheduleRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ScheduleServiceTest.java
일정 다중선택 시 이전에 등록했던 일정이 사라지는 문제 해결
- resolve: #637
=> [BE] 일정 다중선택 시 이전에 등록했던 일정이 사라지는 문제 해결

back/src/main/java/com/woowacourse/teatime/teatime/controller/CrewController.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/SheetAnswerUpdateDto.java, back/src/main/java/com/woowacourse/teatime/teatime/service/SheetService.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/controller/CrewControllerTest.java, back/src/test/java/com/woowacourse/teatime/teatime/fixture/DtoFixture.java, back/src/test/java/com/woowacourse/teatime/teatime/service/SheetServiceTest.java
시트 문항이 선택일 시 빈칸이어도 제출되도록 수정
- resolve: #641
=> [BE] 시트 문항이 선택일 시 빈칸이어도 제출되도록 수정

front/src/components/Textarea/index.tsx, front/src/components/Textarea/styles.ts, front/src/pages/CoachProfile/index.tsx
- 시트 사전 질문 필수여부 색상 변경 
- 필수 red, 선택 gray 색상
resolve: #644
=> 시트 사전 질문 필수여부 색상 변경 

back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/dto/AlarmTargetDto.java, back/src/main/java/com/woowacourse/teatime/teatime/service/dto/SlackAlarmDto.java
async 로직에서 프록시를 전달하는 문제 해결
resolve: #646
=> [BE] async 로직에서 프록시를 전달하는 문제 해결

back/build.gradle, back/src/main/java/com/woowacourse/teatime/auth/config/RedisConfig.java, back/src/main/java/com/woowacourse/teatime/auth/controller/AuthController.java, back/src/main/java/com/woowacourse/teatime/auth/controller/dto/GenerateTokenDto.java, back/src/main/java/com/woowacourse/teatime/auth/controller/dto/LoginResponse.java, back/src/main/java/com/woowacourse/teatime/auth/controller/dto/RefreshAccessTokenResponse.java, back/src/main/java/com/woowacourse/teatime/auth/controller/dto/UserAuthDto.java, back/src/main/java/com/woowacourse/teatime/auth/domain/UserAuthInfo.java, back/src/main/java/com/woowacourse/teatime/auth/exception/WrongCookieTokenException.java, back/src/main/java/com/woowacourse/teatime/auth/infrastructure/ResponseCookieTokenProvider.java, back/src/main/java/com/woowacourse/teatime/auth/repository/UserAuthInfoRepository.java, back/src/main/java/com/woowacourse/teatime/auth/service/LoginService.java, back/src/main/java/com/woowacourse/teatime/auth/service/UserAuthService.java, back/src/main/java/com/woowacourse/teatime/teatime/config/WebConfig.java, back/src/test/java/com/woowacourse/teatime/auth/acceptance/AuthAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/auth/controller/AuthControllerTest.java, back/src/test/java/com/woowacourse/teatime/auth/repository/UserAuthInfoRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/auth/service/UserAuthServiceTest.java, back/src/test/java/com/woowacourse/teatime/auth/support/TestRedisConfig.java, back/src/test/java/com/woowacourse/teatime/teatime/controller/ControllerTestSupporter.java
- redis를 이용하여 토큰을 저장하도록 redis관련 설정들을 해준다.
- 기존 로그인 로직을 새로 구현한다.
- 리프레시 토큰을 이용해 엑세스 토큰을 재발급하고 저장하는 로직을 구현한다.
- 우선 머지 후 리뷰는 추후 완성 되면 진행하겠습니다!
resolve: #650
=> [BE] 리프레시 토큰 구현

front/src/api/auth.ts
=> [FE] login api v2로 변경

front/src/api/index.ts
=> [FE] withCredentials 설정

front/src/api/index.ts
=> [FE] axios defaults 설정 변경

front/src/api/index.ts
=> [FE] axios default 설정 변경

back/src/main/java/com/woowacourse/teatime/teatime/config/WebConfig.java
=> [BE] exposedHeaders 설정 변경

front/src/api/auth.ts, front/src/api/index.ts
=> [FE] login api v2 제거

back/src/main/java/com/woowacourse/teatime/teatime/service/ScheduleService.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ScheduleServiceTest.java
빈 스케줄을 등록해도 기존 스케줄이 삭제되지 않는 에러 해결
=> [BE] 빈 스케줄을 등록해도 기존 스케줄이 삭제되지 않는 에러 해결

front/src/api/auth.ts, front/src/api/index.ts, front/src/typings/domain.ts
=> [FE] 리프레시 토큰 api 연동

back/src/main/java/com/woowacourse/teatime/auth/controller/AuthController.java, back/src/main/java/com/woowacourse/teatime/auth/domain/UserAuthInfo.java, back/src/main/java/com/woowacourse/teatime/auth/service/LoginService.java, back/src/main/java/com/woowacourse/teatime/auth/service/UserAuthService.java
- 토큰 생성 로직을 변경한다.
- 만료된 access token을 보냈을 때 만료 오류가 나는 부분을 삭제한다.
=> [BE] 토큰 생성 로직 변경

back/src/main/java/com/woowacourse/teatime/teatime/domain/Poke.java
Poke 도메인에 JPA Auditing 설정 어노테이션 추가
=> [BE] Poke 도메인에 JPA Auditing 설정 어노테이션 추가

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachProfileResponse.java
코치 프로필 조회시 isPokable 추가
- resolve: #671
=> [BE] 코치 프로필 조회시 isPokable 추가

front/src/api/index.ts, front/src/constants/index.ts
- 토큰 에러 예외사항 추가
- 불필요한 코드 제거
resolve: #675
=> [FE] 토큰 에러 예외사항 추가

front/src/api/index.ts
=> [FE] content type 설정

front/src/components/Card/index.tsx, front/src/components/Card/styles.ts, front/src/pages/CrewMain/index.tsx
=> [FE] 구독하기 아이콘 제거

back/src/main/java/com/woowacourse/teatime/exception/ControllerAdvice.java, back/src/main/java/com/woowacourse/teatime/teatime/exception/CannotPokeException.java, back/src/main/java/com/woowacourse/teatime/teatime/service/PokeService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/dto/poke/PokeSlackAlarmDto.java, back/src/test/java/com/woowacourse/teatime/teatime/service/PokeServiceTest.java
콕 찔러보기 검증로직 추가
- resolve: #683
=> [BE] 콕 찔러보기 검증로직 추가

back/build.gradle
=> [BE] jar 버저닝 포맷 수정

back/build.gradle
=> [BE] jar 파일 버저닝 수정

back/build.gradle
=> [BE] 서브모듈 설정 파일 coptSecret 추가

back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java
=> [BE] 무중단 배포 테스트

front/src/components/Card/styles.ts
=> [FE] 누락된 이미지 사이즈 명시

front/src/api/index.ts
- request interceptor 설정 수정 => content-type 추가부분 제거
- config를 덮어씌우지 않는 방식으로 변경
> 머지후에 `토큰만료후 기존요청 재요청시 content-type 확인하기`
resolve: #694
=> [FE] 인터셉터 설정 수정 

front/src/components/Card/SkeletonCard.tsx, front/src/components/Card/styles.ts, front/src/constants/index.ts, front/src/pages/CrewMain/index.tsx
- 메인화면 새로고침시 스켈레톤 UI를 추가한다.
- before
- after
resolve: #697
=> [FE] 스켈레톤 UI 추가

back/build.gradle
=> [BE] prod 무중단 적용

back/build.gradle, back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java, front/src/App.tsx, front/src/api/index.ts, front/src/components/BoardSelectList/index.tsx, front/src/components/Calendar/index.tsx, front/src/components/Card/SkeletonCard.tsx, front/src/components/Card/index.tsx, front/src/components/Card/styles.ts, front/src/components/DateBox/index.tsx, front/src/components/DateBox/styles.ts, front/src/components/Modal/index.tsx, front/src/components/ReservationTimeList/index.tsx, front/src/components/TimeBox/styles.ts, front/src/components/Title/index.tsx, front/src/components/Title/styles.ts, front/src/constants/index.ts, front/src/context/BoardModeProvider.tsx, front/src/mocks/data.ts, front/src/mocks/handlers.ts, front/src/pages/CoachMain/index.tsx, front/src/pages/CrewMain/index.tsx, front/src/pages/Reservation/index.tsx, front/src/styles/GlobalStyle.ts, front/src/typings/domain.ts
- 무중단 배포 
- 스켈레톤 코드 추가 
- 모바일에서 선택된 보드 상태 저장
=> release: 1.7.0

front/src/pages/Home/index.tsx, front/src/pages/Home/styles.ts
홈화면에서 체험하기 버튼을 통해 데모페이지로 이동할 수 있다.
=> [FE] 체험하기 버튼 추가

front/src/api/auth.ts, front/src/api/index.ts, front/src/components/Header/index.tsx
- 리프레시토큰 db제거를위한 로그아웃 api 연동
resolve:  #704
=> [FE] 로그아웃 api 연동

back/build.gradle
=> [BE] jar 버전 업데이트 1.6.0 -> 1.7.0

README.md, back/build.gradle, back/src/main/java/com/woowacourse/teatime/auth/controller/AuthController.java, back/src/main/java/com/woowacourse/teatime/auth/infrastructure/ResponseCookieTokenProvider.java, back/src/main/java/com/woowacourse/teatime/auth/service/UserAuthService.java, back/src/main/resources/logback-spring.xml, back/src/test/java/com/woowacourse/teatime/auth/controller/AuthControllerTest.java, front/src/api/auth.ts, front/src/api/index.ts, front/src/components/Header/index.tsx, front/src/pages/Home/index.tsx, front/src/pages/Home/styles.ts
- 체험하기 버튼 추가
- 로그아웃 api 추가
- 로그백 설정 수정
=> release: 1.8.0 

front/src/components/ReservationTimeList/index.tsx, front/src/pages/Reservation/index.tsx
isPossible을 이용하여 false일 경우 리턴한다.
resolve: #717
=> [FE] 탭으로 시간선택시 이벤트 발생하는 에러 해결

front/src/App.tsx, front/src/components/ErrorMessage/index.tsx, front/src/components/ErrorMessage/styles.ts, front/src/components/Header/index.tsx, front/src/components/ScheduleTimeList/styles.ts, front/src/components/Sheet/index.tsx, front/src/constants/index.ts, front/src/pages/Certification/index.tsx, front/src/pages/CoachHistory/index.tsx, front/src/pages/CoachMain/index.tsx, front/src/pages/CoachProfile/index.tsx, front/src/pages/CoachSheet/index.tsx, front/src/pages/CrewHistory/index.tsx, front/src/pages/CrewMain/index.tsx, front/src/pages/CrewSheet/index.tsx, front/src/pages/Error/index.tsx, front/src/pages/HistorySheet/index.tsx, front/src/pages/NotFound/index.tsx, front/src/pages/Question/index.tsx, front/src/pages/Reservation/index.tsx, front/src/pages/Schedule/index.tsx, front/src/utils/logError.ts
- 전반적인 에러처리 추가
커스텀 코드가 따로 없으므로, 우선 alert로 에러 상황을 안내하는 경우와 알수없는 에러인 경우로 나누어서 처리했습니다.
resolve: #712
=> [FE] 전반적인 에러처리

front/package-lock.json, front/package.json, front/src/index.tsx, front/src/pages/CrewMain/index.tsx, front/src/utils/logError.ts
- Sentry 적용 및 슬랙 연동
resolve: #721
=> [FE] 에러 모니터링 적용
