back/src/main/java/com/woowacourse/teatime/service/ScheduleService.java, back/src/main/java/com/woowacourse/teatime/util/Date.java, back/src/test/java/com/woowacourse/teatime/acceptance/ScheduleAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
- 코치 일정 조회 시 지난 일정을 제외한 오늘 이후의 일정만 가져오도록 수정
- import.sql 의 더미 데이터와 분리되도록 테스트 수정
LocalTime.MAX 사용 시 23:59:5999999...가 반환됨
따라서 db에 저장 시 올림하여 다음날 00:00:00 로 저장되는 문제 해결 필요
reslove: #15
=> [BE] 코치 일정 조회 시 오늘 이후의 일정만 가져오도록 수정

back/src/main/java/com/woowacourse/teatime/util/Date.java
* 코치 스케줄을 조회할 때 년도에 상관 없이 해당 달의 스케줄을 가져오는 오류 수정
* 코치 스케줄을 조회할 때 년도에 상관 없이 지금 시점 이전의 달을 조회하는 경우 뜨는 오류 수정
resolve: #85
=> [BE] 코치 스케줄 조회 관련 날짜 오류 수정

back/src/test/java/com/woowacourse/teatime/acceptance/ScheduleAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/service/ScheduleServiceTest.java
- 달의 마지막 날에 유동적으로 테스트가 진행될 수 있도록 수정
- 추가적으로 2022년도가 아닌 2023년도 이후에 테스트 진행시 테스트가 깨질 수 있는 문제점 수정
- LocalTime.MAX 를 이용해 DB에 데이터 저장시 다음날로 변경되어 저장되는 문제 해결
resolve: #143
=> [BE] 달의 마지막 날에 테스트가 깨지는 문제 수정

back/src/main/java/com/woowacourse/teatime/domain/Reservation.java, back/src/main/java/com/woowacourse/teatime/domain/ReservationStatus.java, back/src/test/java/com/woowacourse/teatime/domain/ReservationTest.java, back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
- 코치가 IN PROGRESS 상태에서 면담을 취소할 수 있다.
- 크루는 IN PROGRESS 상태에서 면담을 취소할 수 없다.
- 로그인이 들어가면 예약 도메인과 서비스가 많이 바뀔 것으로 예상되므로 로그인 후, 리팩토링이 필수일 것으로 보인다. 
resolve: #152
=> [BE] 코치가 진행 중인 면담을 취소하는 기능

back/src/docs/asciidoc/api.adoc, back/src/main/java/com/woowacourse/teatime/controller/ReservationController.java, back/src/main/java/com/woowacourse/teatime/domain/Reservation.java, back/src/main/java/com/woowacourse/teatime/exception/UnableToDoneReservationException.java, back/src/main/java/com/woowacourse/teatime/service/ReservationService.java, back/src/test/java/com/woowacourse/teatime/acceptance/CoachAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/acceptance/ReservationAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/controller/ReservationControllerTest.java, back/src/test/java/com/woowacourse/teatime/domain/ReservationTest.java, back/src/test/java/com/woowacourse/teatime/fixture/DomainFixture.java, back/src/test/java/com/woowacourse/teatime/service/ReservationServiceTest.java
- 진행 중인 면담을 완료 상태로 변경하는 기능 구현
- 진행 중이지 않은 면담에 대한 요청이 오면 예외 반환
- acceptanceTest에서 service가 사용되고 있는데, 인수 테스트의 목적에 맞는지 고민해보면 좋을 것 같다.
resolve: #170
=> [BE] 진행 중인 면담을 완료하는 기능 구현

front/src/components/BoardItem/index.tsx, front/src/components/CoachTimeList/index.tsx, front/src/components/TimeList/index.tsx, front/src/pages/Coach/index.tsx
- 타임리스트 컴포넌트 리팩토링
- 불필요한 Fragment 제거, 하드코딩 상수 제거
- 코치 메인페이지 리팩토링
- 불필요한 parent 탐색 수정
- 임시 any 타입 제거
- 보드 아이템  **삭제/ 이동/ 정렬** 함수를 분리하여 중복됐던 코드 제거
<br>
- 현재 `보드간` 드래그이동만 가능하고, `보드내` 드래그이동은 불가능하다. 특정 위치(아이템 순서)로 이동도 불가능하다.
- 서버에서 승인된 일정은 정렬해서 주고, 대기중 일정은 들어오는 순서대로 주고있는데 보드내 이동이나 특정 순서로 이동이 필요할까?
- 보드내 이동이 필요하다면 서버에 순서도 저장해야하므로 백엔드와 논의해야할듯
- 아니면 그냥 프론트에서만 특정위치/보드내 이동하는 방법도 있다. 
<br>
resolve: #228
=> [FE] 코치 메인페이지 리팩토링

front/src/components/CoachTimeList/styles.ts
- 코치 타임리스트 스크롤뷰 수정
- 화면 크기에 맞게 시간 리스트가 보이도록 수정
resolve: #230
=> [FE] 캘린더 시간 스크롤 개선 

front/src/components/Board/index.tsx, front/src/components/Board/styles.ts, front/src/components/BoardItem/index.tsx, front/src/styles/theme.ts
- 아이템이 들어갈 보드 컴포넌트의 색상변경
- 아이템이 드래그될 보드의 색상을 조금 진하게 변경했습니다. 드래그는 이정도로 마무리하면 될듯해요
resolve: #239
=> [FE] 보드 컴포넌트 드래그 스타일 추가

back/src/main/java/com/woowacourse/teatime/controller/dto/request/SheetAnswerUpdateDto.java, back/src/main/java/com/woowacourse/teatime/service/ReservationService.java, back/src/test/java/com/woowacourse/teatime/acceptance/CrewAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/controller/CrewControllerTest.java, back/src/test/java/com/woowacourse/teatime/fixture/DtoFixture.java, back/src/test/java/com/woowacourse/teatime/service/SheetServiceTest.java
크루 면담 시트 수정 시 Request에 questionContent를 추가한다.
`/api/crews/me/reservations/{reservationId}`
resolve: #266
=> 크루 면담 시트 수정 시 Resquest에 questionContent 추가

front/package-lock.json, front/package.json, front/webpack.config.ts
- 번들 사이즈 분석 및 개선
- app.bundle.js 사이즈가 너무커서 analyzer로 살펴본결과 app.bundle.js (3mb), index 크기가 2mb
- production 모드 스크립트 추가후 다시 analyzer 결과 app.bundle.js (312kb)
<br>
Optimization 설정에서 splitChunks 옵션 `all`로 100kb 까지 쪼깨는법도 확인해봤는데 minimize, splitChunks같은 옵션들 좀더 알아보고 추후 적용하면 좋을것같아요!
resolve: #274
=> [FE] 번들 사이즈 분석 및 개선

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/ReservationCancelRequest.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindCrewHistoryResponse.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java
- 코치가 크루 히스토리 조회 response에 면담 시트가 포함되도록 수정
resolve: #287
=> [BE] 코치가 크루 히스토리 조회 response 수정

back/src/main/java/com/woowacourse/teatime/auth/infrastructure/PayloadExtractor.java, back/src/main/java/com/woowacourse/teatime/auth/service/AuthService.java, back/src/main/java/com/woowacourse/teatime/auth/support/LoginInterceptor.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/SheetQuestionUpdateDto.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Coach.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Question.java, back/src/main/java/com/woowacourse/teatime/teatime/service/QuestionService.java, back/src/main/java/com/woowacourse/teatime/util/AuthorizationExtractor.java, back/src/test/java/com/woowacourse/teatime/teatime/fixture/DtoFixture.java, back/src/test/java/com/woowacourse/teatime/teatime/service/CoachServiceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/QuestionServiceTest.java
* 코치를 생성할 때 디폴트 시트 질문들 저장하도록 수정한다.
* QuestionService를 만들지말고 SheetService에 넣어야할까?
* SheetService에서 QuestionService를 가지게 하는건 어떨까? (양방향 참조 거의 없을 것 같아서)
* AuthService에서 CoachService와 CrewService를 가지게 해서 찾아오거나 save하게 하는 건 어떨까?
코멘트 부탁!
resolve: #311
=> [BE] 코치 생성 시 시트 질문들을 생성하도록 수정

front/src/utils/date.ts
- 사파리,엣지 등의 브라우저에서 캘린더 날짜가 NaN인 문제 수정
- safari, edge등에서 new Date('YYYY MM') 형식을 읽지못하는 이슈
resolve: #330
=> [FE] startDate의 Date 포맷 변경

front/src/utils/date.ts
- safari, edge등의 브라우저에서 new Date(YYYY-MM-DD)를 읽지못하는 이슈 수정
resolve: #333
=> [FE] new Date 포맷 함수 수정

back/src/main/java/com/woowacourse/teatime/auth/infrastructure/SlackOpenIdAuth.java
* 슬랙에서 제공해주는 프로필 이미지 반환 사이즈를 수정한다. (프론트에서 너무 작게 보임)
* 기존에 로그인 시 무조건 로그를 찍어주고 있었던 문제를 개선한다.
resolve: #345
=> [BE] 프로필 이미지 반환 시 사이즈 수정 및 로그 개선

front/src/components/Board/styles.ts, front/src/components/Sheet/index.tsx
크루 히스토리 내용 보기 오류 수정
- contents -> sheets 로 수정
- 코치 메인 뷰에서 상태 별로 갯수 표시하는 스타일 수정
원인: 보드 아이템이 4개 이상일 경우, 3개만 보이기 때문에 1개가 더 있는지 판단하기 어려움 (갯수에 눈이 잘 안감, 아이템들만 보고 판단하게됨)
해결 방안:
1. 보드 타이틀에서 갯수를 눈에 잘 띄게 한다.
2. 4개 이상일 경우 스크롤이 생긴다.
3. 맨 밑에 보드 아이템이 약간 보이게 한다. 그러면 밑에 아이템들이 더 있구나 알 수 있을듯
일단 보드 갯수 스타일을 약간 수정함
before
4개 이지만 3개로 착각할 수 있음.
after
resolve: #356
=> [FE] 크루 히스토리 내용 보기 오류 수정

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachReservationDtoWithSheetStatus.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachReservationDtoWithoutSheetStatus.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachReservationsResponse.java
* response dto에서 sheetStatus를 포함하도록 수정
resolve: #383
=> [BE] 코치 메인 뷰에서 승인 전 면담에도 시트 상태를 포함해 반환하도록 수정

front/src/components/ReservationTimeList/index.tsx, front/src/components/Sheet/index.tsx, front/src/components/TableRow/index.tsx, front/src/pages/CrewSheet/index.tsx
- 버튼을 클릭하면 바로 제출된다. 그래서 내용을 제출하면 수정이 안되기 때문에 confirm이 필요하다고 판단 
resolve: #406
=> [FE] 면담시트 제출 로직 변경 및 상태에 따라 면담 삭제 수정

back/src/main/java/com/woowacourse/teatime/teatime/domain/Reservation.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java, back/src/test/java/com/woowacourse/teatime/teatime/infrastructure/SchedulerTest.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/ReservationRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
* 면담을 진행 중 상태로 바꿀 때 원래 서비스 로직에서는 reservation 리스트를 돌면서 면담 시간이 지난 예약들만 바꿔주었다. 
* 하지만 이렇게 하는 것은 외부에서 reservation의 메서드를 호출 할 때 검증 로직이 없기 때문에 위험하다고 판단
* 그래서 검증 로직을 추가했지만 그렇게 하면 시간이 지나지 않은 reservation에 대해서 항상 exception이 발생
* 따라서 검증을 거치면서 무조건적인 exception을 피해 갈 수 있는 방향으로 fix함
* ReservationService의 진행중으로 업데이트하는 로직 개선
* ReservationRepository에서 인자로 상태를 받아서 승인된 면담을 불러오는 메서드를 오늘 날짜의 승인된 면담으로 불러오는 메서드로 변경
* 기존 메서드를 없앰에 따라 테스트코드에서 사용하고 있던 의존성 끊기
=> [BE] 면담을 진행중 상태로 바꿀 때 에러가 발생하는 문제 해결 및 리팩터링

front/src/components/Board/styles.ts, front/src/components/Header/index.tsx, front/src/components/ReservationTimeList/index.tsx, front/src/components/TableRow/index.tsx, front/src/hooks/useBoolean.ts, front/src/pages/Reservation/index.tsx, front/src/pages/Schedule/index.tsx
- 보드컴포넌트 스크롤바 추가
- useBoolean 훅은 훅이름에 맞게 _openElement/closeElement_ 에서 _setTrue/setFalse_ 로 리턴함수 네이밍만 변경했습니당
- 스크롤바 overflow y축, 스타일만 수정했는데 사진처럼 보드 아이템 많을때만 보이는지 확인해주세요! intersectionObserver는 굳이 안써도 될거같네요
resolve: #441
=> [FE] 보드컴포넌트 스크롤바 추가

front/src/api/auth.ts, front/src/api/coach.ts, front/src/api/crew.ts, front/src/api/index.ts, front/src/api/reservation.ts, front/src/components/Header/index.tsx, front/src/components/ReservationTimeList/index.tsx, front/src/components/ScheduleTimeList/index.tsx, front/src/components/TableRow/index.tsx, front/src/pages/Certification/index.tsx, front/src/pages/CoachHistory/index.tsx, front/src/pages/CoachMain/index.tsx, front/src/pages/CoachSheet/index.tsx, front/src/pages/CrewHistory/index.tsx, front/src/pages/CrewMain/index.tsx, front/src/pages/CrewSheet/index.tsx, front/src/pages/HistorySheet/index.tsx, front/src/pages/Reservation/index.tsx, front/src/pages/Schedule/index.tsx, front/src/typings/domain.ts
- axios default 헤더 설정
- token이 존재하면 default header를 설정하도록 추가하였습니다.
- api 함수 분리
- api 함수를 `api/도메인`별로 분리했습니다. 분리 기준은 api 명세서 기준이고 순서도 노션과 동일합니다.
- 함수 리팩토링
- 취소 api로 변경되었으로 핸들러 네이밍을 `deleteReservation` -> `handleCancelReservation` 로 수정했습니다.
- 취소 api 아래에있던 setHistoryList 부분을 status를 받아서 상태를 변경하는 `changeHistoryStatus`  함수로 분리하였습니다.
```js
// before
const deleteReservation = async (reservationId: number) => {
try {
await api.delete(`/api/v2/reservations/${reservationId}`, {
headers: {
Authorization: `Bearer ${userData?.token}`,
},
});
setHistoryList((prevHistory) => {
return prevHistory.map((history) => {
if (history.reservationId === reservationId) {
history.status = 'CANCELED';
}
return history;
});
});
showSnackbar({ message: '취소되었습니다. ❎' });
} catch (error) {
//...
}
```
```js
// after …
```
=> [FE] api 함수 분리 및 default header 설정

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CrewFindOwnHistoryResponse.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/CanceledSheet.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/CanceledSheetRepository.java
* 크루가 자신의 히스토리 조회할 때 코치이름이 아닌 크루이름을 보내주는 에러 수정
resolve: #465
=> [BE] 크루가 자신의 히스토리 조회할 때 코치이름이 아닌 크루이름을 보내주는 에러 수정

back/src/main/java/com/woowacourse/teatime/exception/ControllerAdvice.java, back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java
- **불필요한 트랜잭션 전파 옵션 제거**
비동기로 처리하였기 때문에 트랜잭션 전파 옵션이 불필요할 것으로 보여 제거하였다.
- **외부 라이브러리 에러 custom Exception으로 관리**
외부 라이브러리 에러를 잡지 않고 기존처럼 로그로 찍는 것도 좋지만, 
커스텀 예외로 잡아서 ControllerAdvice에서 처리하는 것이 적절한 것으로 판단된다. 또한 이렇게 하면 특정 사항(알람 전송이 실패한 케이스)에 테스트를 할 수 없다.
- SlackAlarmException 던져서 예약 처리 확인하는 service 테스트 살림 
- 차후 알람 전송 이력을 db에 따로 저장해야 할 것으로 보입니다. 
reslove: #489
=> [BE] SlackAlarmException 적용 및 불필요한 트랜잭션 전파 옵션 제거

front/src/components/Sheet/index.tsx, front/src/components/Textarea/index.tsx, front/src/components/Textarea/styles.ts, front/src/pages/CrewSheet/index.tsx
- textarea 자동 높이 조절 기능 추가
- 보기 전용 시트 스타일 수정
- 작성중인 시트에도 뒤로가기 추가
자동 높이 조절 보단 height를 높게 주고 사이즈 조절이 가능하도록 함
=> [FE] 면담 시트 작성 시 자동 높이 조절 기능 추가

front/src/components/BackButton/styles.ts, front/src/components/Board/index.tsx, front/src/components/Board/styles.ts, front/src/components/DateBox/styles.ts, front/src/components/Frame/styles.ts, front/src/components/ReservationInfo/styles.ts, front/src/components/ReservationTimeList/styles.ts, front/src/components/ScheduleTimeList/index.tsx, front/src/components/ScheduleTimeList/styles.ts, front/src/components/SelectList/index.tsx, front/src/components/SelectList/styles.ts, front/src/components/Sheet/styles.ts, front/src/components/TableRow/styles.ts, front/src/hooks/useWindowSize.ts, front/src/index.tsx, front/src/pages/CoachHistory/index.tsx, front/src/pages/CoachMain/index.tsx, front/src/pages/CoachMain/styles.ts, front/src/pages/CrewHistory/index.tsx, front/src/pages/CrewHistory/styles.ts, front/src/pages/Reservation/index.tsx, front/src/pages/Schedule/index.tsx, front/src/styles/common.ts, front/src/styles/theme.ts
- 코치 메인 (보드) 모바일 뷰 구현
- 모바일에서 보드 이름을 클릭하는 셀렉트 컴포넌트를 추가했습니다. 
- 시트뷰, 히스토리뷰 모바일 뷰 구현
- 모바일에서 히스토리 뷰는 크기를 일부 조정했고 시트뷰는 왼쪽 예약정보 쪽을 상단으로 옮겼습니다.
- 칸반보드
- 히스토리
- 시트
resolve: #510
=> [FE] 코치 페이지 모바일뷰 구현

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CoachFindOwnHistoryResponse.java
response에 crewId 필드 추가
resolve: #506
=> [BE] 코치 히스토리 조회시 response에 crewId를 포함하도록 수정

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/CrewFindOwnSheetResponse.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/CrewAcceptanceTest.java
* CrewFindOwnSheetResponse에 ReservationStatus를 추가하고 기존 status 네이밍을 sheetStatus로 바꾼다.
resolve: #527
=> [BE] 크루 자신의 면담 시트를 조회하는 응답에 ReservationStatus를 포함하도록 수정

back/src/main/java/com/woowacourse/teatime/auth/support/LoginInterceptor.java, back/src/main/java/com/woowacourse/teatime/teatime/aspect/LoggingInterceptor.java, back/src/main/java/com/woowacourse/teatime/teatime/aspect/QueryCountInspector.java, back/src/main/java/com/woowacourse/teatime/teatime/config/HibernateConfig.java, back/src/main/java/com/woowacourse/teatime/teatime/config/WebConfig.java, back/src/test/java/com/woowacourse/teatime/teatime/aspect/QueryCountInspectorTest.java, back/src/test/java/com/woowacourse/teatime/teatime/controller/ControllerTestSupporter.java
- 요청이 처리되고 응답되는데 까지 걸리는 시간을 로깅하는 기능 구현
- 요청에 의해 발생한 쿼리가 몇 개인지 로깅하는 기능 구현
resolve: #525
=> [BE] Request 마다 쿼리 개수를 로깅하는 기능 구현

back/src/main/java/com/woowacourse/teatime/teatime/aspect/LoggingInterceptor.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/CanceledReservation.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Reservation.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/CanceledSheetRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/QuestionRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ReservationRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/SheetRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/service/QuestionService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ReservationService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/ScheduleService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/SheetService.java, back/src/test/java/com/woowacourse/teatime/teatime/fixture/DomainFixture.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/CanceledSheetRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/ReservationRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/ScheduleRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/SheetRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/QuestionServiceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ScheduleServiceTest.java
- 조건이 3개 이상일 경우 @Query 이용한 JPQL 사용(가독성 up)
- N+1 분석 및 해결 
- JDBC 도입에 대한 고민 
- QueryDsl 적용에 대해 생각해 보기
- 페이징 처리에 대해 생각해 보기 
....
resolve: #530
=> [BE] JPA 성능 최적화 

back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/ScheduleFindResponse.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/ScheduleRepository.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ScheduleServiceTest.java
- 크루가 코치 스케쥴 조회할 때 오름차순으로 조회되도록 수정
resolve: #550
=> [BE] 크루가 코치 스케쥴 조회할 때 오름차순으로 조회되도록 수정

front/src/components/Calendar/index.tsx
- 이미 지난달 스케쥴 조회요청이 가능한 문제 수정 
- 기존에 비교했던 방식: `new Date(년-월)` vs `new Date()`
```js
new Date('2022-10') // Sat Oct 01 2022 09:00:00 GMT+0900 (한국 표준시) (년-월만 넣게되면 기본적으로 9시간이 더해짐)
new Date() // Sat Oct 01 2022 02:01:19 GMT+0900 (한국 표준시) (현재 콘솔을 찍은 시간)
```
- 수정한 방식
`startDate.getTime() - 9시간` 과 `new Date().getTime()`을 비교해서 
정확히 10월 1일이 되면 이전달 버튼을 비활성화하도록 변경
resolve: #566
=> [FE] 캘린더 이전 월 이동 관련 버그 수정

front/src/pages/CrewMain/index.tsx, front/src/pages/Reservation/index.tsx, front/src/pages/Reservation/styles.ts
- 해당 코치 이미지로 표시하기
- 반응형 대응
- 크루 메인페이지에서 코치리스트가 없으면 빈 내용 표시
resolve: #568
=> [FE] 면담 예약 페이지에서 해당 코치 이미지 표시하기

.github/release-config.yml, .github/workflows/release-drafter.yml
- [시멘틱 버저닝](https://semver.org/lang/ko/) 릴리즈 자동화
- main으로 push할때 새로운 릴리즈가 생성되도록 설정
- `main`으로 release PR 만들때 올릴 버전에따라 `Labels`를 `major, minor, patch` 중에 하나만 지정하면 됩니다.
- 그러면 각자 브랜치에서 develop으로 pr 올렸을때 지정한 라벨(기능,수정)에 따라 pr 제목들이 릴리즈 노트에 표시됩니다.
<br>
<br>
resolve: #574
=> [ALL] release 자동화

front/src/components/Calendar/styles.ts, front/src/components/DateBox/styles.ts, front/src/components/TableRow/styles.ts, front/src/pages/CrewHistory/styles.ts, front/src/pages/CrewMain/styles.ts
- 소형 모바일 사이즈(<=375px)에 대한 스타일 대응
- 히스토리 사이즈 조정
- 캘린더 사이즈 조정
- 코치 목록 사이즈 조정
- 히스토리에서 닉네임이 길어지는 경우 ellipsis(...)처리
|before|after|
|------|---|
|<img width="374" alt="스크린샷 2022-10-04 오전 12 21 41" src="https://user-images.githubusercontent.com/48676844/193615157-17fd961e-b63f-4c14-a921-cf2256e103d8.png">|<img width="416" alt="iphone5-SE" src="https://user-images.githubusercontent.com/48676844/193613817-80c8a13c-71a0-498a-b9a4-fc5e325eb2df.png">
|<img width="377" alt="스크린샷 2022-10-04 오전 12 21 49" src="https://user-images.githubusercontent.com/48676844/193615481-ffb3b419-10dc-45ca-8713-b9ee0bce4a63.png">|<img width="370" alt="스크린샷 2022-10-04 오전 12 19 35" src="https://user-images.githubusercontent.com/48676844/193614427-6147e4f9-b22f-4e61-abfd-0dc797381b23.png">|
| …
=> [FE] 소형 모바일 사이즈 대응

front/src/components/Title/styles.ts
title 중앙이 안맞는 부분 수정
- before
- after
=> [FE] 캘린더 Title 정렬 수정

back/src/docs/asciidoc/index.adoc, back/src/docs/asciidoc/question.adoc, back/src/main/java/com/woowacourse/teatime/auth/service/AuthService.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/QuestionController.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/request/SheetQuestionUpdateRequest.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/SheetQuestionResponse.java, back/src/main/java/com/woowacourse/teatime/teatime/controller/dto/response/SheetQuestionsResponse.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/CanceledReservation.java, back/src/main/java/com/woowacourse/teatime/teatime/domain/Question.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/QuestionRepository.java, back/src/main/java/com/woowacourse/teatime/teatime/repository/jdbc/QuestionDao.java, back/src/main/java/com/woowacourse/teatime/teatime/service/QuestionService.java, back/src/main/java/com/woowacourse/teatime/teatime/service/SheetService.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/QuestionAcceptanceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/fixture/DomainFixture.java, back/src/test/java/com/woowacourse/teatime/teatime/fixture/DtoFixture.java, back/src/test/java/com/woowacourse/teatime/teatime/repository/QuestionRepositoryTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/QuestionServiceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/ReservationServiceTest.java, back/src/test/java/com/woowacourse/teatime/teatime/service/SheetServiceTest.java
- 코치가 시트 지 질문을 수정할 수 있다. 
- 질문의 개수를 정할 수 있고 내용도 수정할 수 있다. 
- 필수 여부를 체크할 수 있다. 
- 자신의 시트 질문지를 조회할 수 있다. 
현재 크루 및 코치가 시트를 조회할 때도 필수 여부(isRequired)를 dto에 추가해야 하는데 `files changed` 가 생각보다 많아져서  나눠서 pr하겠습니다.
=> [BE] 시트 지 질문 필수 여부 체크 및 목록 조회/수정

back/src/main/java/com/woowacourse/teatime/teatime/service/AlarmService.java, back/src/test/java/com/woowacourse/teatime/teatime/acceptance/ReservationAcceptanceTest.java
- 알람이 가지 않아도 시트 제출 처리가 안되는 것이 비효율적이라 판단이 되어 비동기로 처리 
- 이전에 비동기 설정을 해놔서 애노테이션 하나로 해결
++ Acceptance test 알람 모킹 
사실 테스트에서 오리의 알람 api를 무분별하게 사용하고 있다는 제보에 의해 ReservationServiceTest에서 AlramService를 모킹하려고 브랜치를 팠다. 
하지만 이전에 알람 에러 상황 태스트를 짜기 위해 AlramService를 @MockBean 애노테이션을 이용해서 처리해주고 있었다. AlramService를 mock bean으로 사용하고 있더라도 알람 로직이 실행되는 메서드를 doNothing이나 willReturn(null)로 따로 스터빙해줘야 알람로직을 안타는 줄 알았지만 @MockBean 애노테이션 자체로 모킹이 되고 있었다.(디버깅을 통해 확인해봄, @MockBean을 때면 알람 로직을 그대로 타는 것도 확인)🤭 
그럼 10000건의 알람 api 호출은 뭘까요?
resolve: #626
=> [BE] 시트 제출할 때 알람 로직 비동기로 처리

front/src/components/Sheet/index.tsx, front/src/components/Textarea/index.tsx, front/src/components/Textarea/styles.ts, front/src/typings/domain.ts
- 시트 질문 항목에 필수 여부를 표시
- 선택사항은 작성하지 않아도 되도록 검증 로직 일부 수정
resolve: #639
=> [FE] 시트 질문 항목의 필수 여부 표시 
